
#  global_config

global_config:
  nom: Madelaine
  prenom: Manfred
  freres:
    - Morgan
    - Ruben
  test:
    - obj:
      - o
      - b
      - j

    - trucs:
      - he
      - ha
      - hi
